Mobile friendly "Find Project"-page with infinite scroll
Ownemployed-Team/ownemployed pull request #25
Opened 2020-05-31 21:15 UTC by karvex

Not finished yet. Still waiting for backend things before I can "sew in the bags together".
Graphql getProjects function needs:
- limit+skip working.
- input params search, sector, skills, location, status. search-params should search where ilike name/sector/skills/location/status

2020-06-01 10:53 UTC, nopestack requested changes

2020-06-01 10:53 UTC, nopestack commented on package.json
> +        "facepaint": "^1.2.1",
Why is this required?

2020-06-01 10:53 UTC, nopestack commented on src/components/ProjectFilter.tsx
> +    const mq = facepaint([
This was already implemented by @tdubreucq on `theme.ts` and also Rebass has responsive capabilities baked in (via passing an array of values that correspond to each breakpoint defined in the theme object)

2020-06-01 18:52 UTC, karvex commented on src/components/ProjectFilter.tsx
> +    const mq = facepaint([
@nopestack I needed to find a way to return pure css with media queries to react-select. Any suggestion would be nice here. I couldn't find a way to return pure css with media queries to react-select, because react-select and rebass clash a little bit.

2020-06-03 08:36 UTC, nopestack approved these changes

2020-06-03 08:36 UTC, nopestack commented on src/components/ProjectFilter.tsx
> +        theme.breakpoints.map(breakpoint => `@media(min-width: ${breakpoint})`)
Nice 👍

2020-06-03 20:43 UTC, merged