Edit profile page
Ownemployed-Team/ownemployed pull request #30
Opened 2020-06-04 22:10 UTC by karvex

- Added autosave for prettier.
- Some refactor.
- Added Edit profile page.

2020-06-04 22:21 UTC, nopestack requested changes
Overall great work. I'm curious as to why the boxed layout is not desired in the pages it was removed? I recall needing to have a fullwidth layout on `home.tsx` because the spec required fullwidth sections in there, but the mockups seem to maintain a consistent content width limit across all other pages.

2020-06-04 22:21 UTC, nopestack commented on src/pages/404/404.tsx
> +        <Layout>
Why was `boxed` removed with no apparent change to the page's structure?

2020-06-04 22:21 UTC, nopestack commented on ownemployed.code-workspace
> +{
This file seems to be VSCode specific and not necessary for the application to run. Would you remove it?

2020-06-04 22:25 UTC, karvex commented on src/pages/404/404.tsx
> +        <Layout>
boxed-attribute forced Main component to have "margin: auto". That destroys the Main child if they don't have a fixed width or child with elements that takes the whole width.

2020-06-04 22:26 UTC, karvex commented on ownemployed.code-workspace
> +{
Yes, can remove it and add it to .gitignore.

2020-06-07 09:17 UTC, nopestack approved these changes

2020-06-07 09:17 UTC, merged