Health check benjamin
Ownemployed-Team/ownemployed pull request #41
Opened 2020-06-08 16:10 UTC by BenjaminRasmussen

2020-06-08 21:21 UTC, nopestack requested changes
Please remove `package-lock.json` as we use yarn and we already have a `yarn.lock` and these would conflict upon deployment.

2020-06-08 21:21 UTC, nopestack commented on src/utils/healthCheck/healthAudit.ts
> +import { useAuth0 } from './../../lib/react-auth0-spa'
Please use absolute paths to avoid this

2020-06-10 08:37 UTC, BenjaminRasmussen commented on src/utils/healthCheck/healthAudit.ts
> +import { useAuth0 } from './../../lib/react-auth0-spa'
I didn't finish any of this code I was told to drop it and leave it as is and go on to something else while leaving the old branch here. Dont read any of this

2020-06-10 10:15 UTC, nopestack commented
I'm closing this PR as it's a pretty substantial change that requires attention and we're focusing on other priorities at the moment. We can reopen and revisit this at a later date to follow up this conversation

2020-06-10 10:15 UTC, closed without merging